nodeLinker: node-modules

npmRegistryServer: https://art.lmru.tech/api/npm/npm-wms

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
